run-name: Demo of printing text by @${{ github.actor }} ðŸš€
on: push()

jobs:

build:
runs-on: ubuntu-latest # Use windows-latest for PowerShell

steps:

- name: Check Ubuntu Version
run: |
        echo "--- Using lsb_release -a ---"
        lsb_release -a
        echo "--- Using cat /etc/os-release ---"
        cat /etc/os-release
        run: echo "Runner OS: ${{ runner.os }}"


-name: get all files in repository 
run: git ls-files

-name: get sha commit version
run: echo ${{ github.sha }}
-name: print files
run: test.sh

-name: Print a simple message (Bash)
run: echo "Hello"

env:
        FIRST_NAME: "Amir"
        steps:
                -name: Print variable on Windows (CMD syntax)
                run: echo "The value is %FIRST_NAME%"
                shell: cmd
                -name: Set and Print a Local Variable
              run: |
      # Sets a variable 'Last Name' only available for this run block
        last_name="Lustigman" echo "Inside the step: $last_name"
      # This variable is lost after this step finishes
        shell: bash

name: Use a secret in a command
    # Set the secret as an environment variable in the step
env:
      MY_PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
run: |
      # The value of $MY_PHONE_NUMBER is available to your script
      # but will be masked in the logs.
      echo "Calling phone number with token: $MY_PHONE_NUMBER"
      # Pass the token securely to your application or a command
      ./my-app --token="$MY_PHONE_NUMBER"
